-- 20261006090100_se_people.sql
-- Contacts (people across events), registrations, access tokens, devices, custom form fields.

CREATE TABLE IF NOT EXISTS se_contacts (
    id                    INT UNSIGNED NOT NULL AUTO_INCREMENT,
    phone_e164            VARCHAR(16)  NOT NULL,
    phone_display         VARCHAR(24)  NULL,
    sms_capable           TINYINT(1)   NOT NULL DEFAULT 1,
    first_name            VARCHAR(80)  NOT NULL,
    last_name             VARCHAR(80)  NOT NULL DEFAULT '',
    email                 VARCHAR(190) NULL,
    gender                ENUM('Male','Female') NULL,
    member_user_id        INT UNSIGNED NULL,
    member_ambiguous      TINYINT(1)   NOT NULL DEFAULT 0,
    member_checked_at     DATETIME     NULL,
    consent_followup      TINYINT(1)   NOT NULL DEFAULT 0,
    consent_followup_at   DATETIME     NULL,
    consent_text_hash     CHAR(64)     NULL,
    opted_out_at          DATETIME     NULL,
    erased_at             DATETIME     NULL,
    created_at            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_se_contacts_phone (phone_e164),
    KEY idx_se_contacts_member (member_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS se_registrations (
    id                           INT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_id                     INT UNSIGNED NOT NULL,
    contact_id                   INT UNSIGNED NOT NULL,
    reg_code                     CHAR(8)      NOT NULL,
    ref_code                     CHAR(6)      NOT NULL,
    status                       ENUM('confirmed','waitlisted','cancelled','removed') NOT NULL,
    seat_pool                    ENUM('online','walkin') NULL,
    channel                      ENUM('portal','walkin_self','walkin_desk','studio') NOT NULL DEFAULT 'portal',
    is_member                    TINYINT(1)   NOT NULL DEFAULT 0,
    is_test                      TINYINT(1)   NOT NULL DEFAULT 0,
    first_name                   VARCHAR(80)  NOT NULL,
    last_name                    VARCHAR(80)  NOT NULL DEFAULT '',
    gender                       ENUM('Male','Female') NULL,
    email                        VARCHAR(190) NULL,
    display_name                 VARCHAR(40)  NOT NULL,
    name_correction              VARCHAR(160) NULL,
    how_heard                    VARCHAR(30)  NULL,
    how_heard_other              VARCHAR(80)  NULL,
    src                          VARCHAR(20)  NULL,
    referred_by_registration_id  INT UNSIGNED NULL,
    companion_of_registration_id INT UNSIGNED NULL,
    karaoke_interest             TINYINT(1)   NOT NULL DEFAULT 0,
    wants_visit                  TINYINT(1)   NOT NULL DEFAULT 0,
    answers_json                 TEXT         NULL,
    team_id                      INT UNSIGNED NULL,
    team_assigned_at             DATETIME     NULL,
    player_no                    INT UNSIGNED NULL,
    first_checkin_at             DATETIME     NULL,
    confirmed_at                 DATETIME     NULL,
    waitlisted_at                DATETIME     NULL,
    cancelled_at                 DATETIME     NULL,
    cancelled_by                 ENUM('self','crew','system') NULL,
    cancel_reason                VARCHAR(160) NULL,
    ip_hash                      CHAR(64)     NULL,
    created_at                   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_se_reg_contact (event_id, contact_id),
    UNIQUE KEY uniq_se_reg_code (event_id, reg_code),
    UNIQUE KEY uniq_se_reg_ref (event_id, ref_code),
    UNIQUE KEY uniq_se_reg_player (event_id, player_no),
    KEY idx_se_reg_status (event_id, status, seat_pool),
    KEY idx_se_reg_waitlist (event_id, status, waitlisted_at),
    KEY idx_se_reg_team (event_id, team_id),
    KEY idx_se_reg_contact (contact_id),
    CONSTRAINT fk_se_reg_event FOREIGN KEY (event_id) REFERENCES se_events (id) ON DELETE CASCADE,
    CONSTRAINT fk_se_reg_contact FOREIGN KEY (contact_id) REFERENCES se_contacts (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS se_access_tokens (
    id               INT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_id         INT UNSIGNED NOT NULL,
    registration_id  INT UNSIGNED NOT NULL,
    purpose          ENUM('manage','transfer') NOT NULL,
    token_hash       CHAR(64)     NOT NULL,
    created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at       DATETIME     NOT NULL,
    last_used_at     DATETIME     NULL,
    used_at          DATETIME     NULL,
    revoked_at       DATETIME     NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_se_tokens_hash (token_hash),
    KEY idx_se_tokens_reg (registration_id),
    KEY idx_se_tokens_expiry (expires_at),
    CONSTRAINT fk_se_tokens_event FOREIGN KEY (event_id) REFERENCES se_events (id) ON DELETE CASCADE,
    CONSTRAINT fk_se_tokens_reg FOREIGN KEY (registration_id) REFERENCES se_registrations (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS se_devices (
    id               INT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_id         INT UNSIGNED NOT NULL,
    registration_id  INT UNSIGNED NULL,
    token_hash       CHAR(64)     NOT NULL,
    mode             ENUM('full','readonly') NOT NULL DEFAULT 'full',
    joined_games_at  DATETIME     NULL,
    ua_hash          CHAR(64)     NULL,
    created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at     DATETIME     NULL,
    revoked_at       DATETIME     NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_se_devices_token (token_hash),
    KEY idx_se_devices_reg (registration_id),
    KEY idx_se_devices_games (event_id, joined_games_at),
    CONSTRAINT fk_se_devices_event FOREIGN KEY (event_id) REFERENCES se_events (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS se_form_fields (
    id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_id     INT UNSIGNED NOT NULL,
    field_key    VARCHAR(40)  NOT NULL,
    label        VARCHAR(160) NOT NULL,
    type         VARCHAR(20)  NOT NULL,
    options_json TEXT         NULL,
    is_required  TINYINT(1)   NOT NULL DEFAULT 0,
    placeholder  VARCHAR(120) NULL,
    help_text    VARCHAR(255) NULL,
    audience     ENUM('everyone','guests','members') NOT NULL DEFAULT 'everyone',
    sort_order   INT          NOT NULL DEFAULT 0,
    is_active    TINYINT(1)   NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_se_form_fields_key (event_id, field_key),
    CONSTRAINT fk_se_form_fields_event FOREIGN KEY (event_id) REFERENCES se_events (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
