<?php
// /includes/special_events/games_engine.php
// Round state machine, timing and public game views.

function se_game_elapsed(int $client, int $server, int $duration): int { return max(0, min($duration, min($client, $server))); }
function se_buzz_effective(int $client, int $opens, int $received): int { return max($opens, min($client, $received)); }
function se_buzz_order(array $buzzes): array { usort($buzzes, static fn($a,$b)=>[$a['effective_ms'],$a['received_at']??'',(int)($a['team_order']??0)] <=> [$b['effective_ms'],$b['received_at']??'',(int)($b['team_order']??0)]); return $buzzes; }
function se_game_settings(array $game): array { return json_decode((string)($game['settings_json']??'{}'),true) ?: []; }
function se_round_item(PDO $pdo, array $round): ?array { if(empty($round['deck_item_id']))return null;$s=$pdo->prepare('SELECT * FROM se_deck_items WHERE id=?');$s->execute([(int)$round['deck_item_id']]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)return null;$r['payload']=json_decode($r['payload_json'],true)?:[];return $r; }
function se_round_next(PDO $pdo,array $event,array $game,int $actor,bool $test=false):array { $pdo->beginTransaction();try{$s=$pdo->prepare("SELECT COALESCE(MAX(round_no),0)+1 FROM se_rounds WHERE game_id=?");$s->execute([(int)$game['id']]);$no=(int)$s->fetchColumn();$s=$pdo->prepare("SELECT deck_item_id FROM se_game_items WHERE game_id=? ORDER BY sort_order LIMIT 1 OFFSET ".($no-1));$s->execute([(int)$game['id']]);$item=$s->fetchColumn();if(!$item)throw new SeRuleException('No approved deck item remains.','NO_ITEMS');$s=$pdo->prepare('INSERT INTO se_rounds(event_id,game_id,round_no,deck_item_id,is_test) VALUES(?,?,?,?,?)');$s->execute([(int)$event['id'],(int)$game['id'],$no,(int)$item,$test?1:0]);$id=(int)$pdo->lastInsertId();$pdo->commit();return ['id'=>$id,'round_no'=>$no,'state'=>'pending'];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
function se_round_arm(PDO $pdo,array $event,int $roundId,int $preroll,int $duration,?int $expected,int $actor):array { $now=se_epoch_ms();$preroll=max(2500,$preroll);$s=$pdo->prepare('SELECT r.*,g.settings_json,g.type FROM se_rounds r JOIN se_games g ON g.id=r.game_id WHERE r.id=? AND r.event_id=?');$s->execute([$roundId,(int)$event['id']]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)throw new SeNotFoundException('Round not found.');if($r['state']!=='pending')throw new SeRuleException('That round has already started.','STALE_STATE');$opens=$now+$preroll;$closes=$opens+$duration;$elig=[];if(se_table_exists($pdo,'se_registrations')){$q=$pdo->prepare("SELECT team_id,COUNT(*) n FROM se_registrations WHERE event_id=? AND status='confirmed' AND team_id IS NOT NULL GROUP BY team_id");$q->execute([(int)$event['id']]);$elig=$q->fetchAll(PDO::FETCH_KEY_PAIR);}$dt=static fn($ms)=>date('Y-m-d H:i:s.',intdiv($ms,1000)).str_pad((string)($ms%1000),3,'0',STR_PAD_LEFT);$s=$pdo->prepare("UPDATE se_rounds SET state='armed',arm_at=?,opens_at=?,closes_at=?,eligible_json=? WHERE id=? AND state='pending'");$s->execute([$dt($now),$dt($opens),$dt($closes),se_json_encode($elig),$roundId]);if(!$s->rowCount())throw new SeRuleException('The round changed. Refresh and try again.','STALE_STATE');return ['id'=>$roundId,'state'=>'armed','arm_ms'=>$now,'opens_ms'=>$opens,'closes_ms'=>$closes];}
function se_round_transition(PDO $pdo,int $roundId,string $to,int $actor,string $reason=''):array { $allowed=['pending'=>['armed','void'],'armed'=>['open','locked','void'],'open'=>['locked','void'],'locked'=>['revealed','void'],'revealed'=>['scored','void'],'scored'=>['void']];$s=$pdo->prepare('SELECT * FROM se_rounds WHERE id=?');$s->execute([$roundId]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)throw new SeNotFoundException('Round not found.');if(!in_array($to,$allowed[$r['state']]??[],true))throw new SeRuleException('That round cannot make that transition.','STALE_STATE');$col=['locked'=>'locked_at','revealed'=>'revealed_at'][$to]??null;$sql='UPDATE se_rounds SET state=?';$args=[$to];if($col){$sql.=', '.$col.'=NOW(3)';}if($to==='void'){$sql.=',void_reason=?';$args[]=$reason;}$sql.=' WHERE id=? AND state=?';$args[]=$roundId;$args[]=$r['state'];$s=$pdo->prepare($sql);$s->execute($args);if(!$s->rowCount())throw new SeRuleException('The round changed.','STALE_STATE');return ['id'=>$roundId,'state'=>$to];}
function se_round_public(PDO $pdo,array $round,bool $reveal=false):array { $item=se_round_item($pdo,$round);$p=$item['payload']??[];$type=$item['content_type']??'mcq';$view=['content_type'=>$type];foreach(['prompt','choices','emojis','lead','clues'] as $k)if(isset($p[$k]))$view[$k]=$p[$k];if(!$reveal&&isset($view['clues']))$view['clues']=array_slice($view['clues'],0,(int)($round['state_json']??0));if($reveal){$result=json_decode((string)($round['result_json']??'{}'),true)?:[];$view['reveal']=$result;}unset($view['answer'],$view['accept'],$view['phrase']);return $view;}
function se_games_reset(PDO $pdo,array $event,int $actor):int { $id=(int)$event['id'];$n=0;foreach(['se_score_events','se_answers','se_buzzes','se_rounds','se_survey_responses'] as $t){if(!se_table_exists($pdo,$t))continue;$s=$pdo->prepare("DELETE FROM {$t} WHERE event_id=? AND is_test=1");try{$s->execute([$id]);$n+=$s->rowCount();}catch(Throwable $e){if($t==='se_score_events'){ $s=$pdo->prepare('DELETE FROM se_score_events WHERE event_id=? AND idempotency_key LIKE ?');$s->execute([$id,'TEST%']);$n+=$s->rowCount();}}}return $n;}

function se_game_join(PDO $pdo,array $event,array $reg):array { $s=$pdo->prepare("UPDATE se_devices SET joined_games_at=NOW() WHERE event_id=? AND registration_id=? AND mode='full'");$s->execute([(int)$event['id'],(int)$reg['id']]);if(!$s->rowCount())throw new SeRuleException('Check in first to join the games.','NOT_CHECKED_IN');return ['joined'=>true,'games'=>se_game_list($pdo,(int)$event['id'])]; }
function se_game_answer(PDO $pdo,array $event,array $reg,array $in):array { $roundId=se_int($in['round_id']??0,0);$s=$pdo->prepare('SELECT r.*,g.type,g.settings_json FROM se_rounds r JOIN se_games g ON g.id=r.game_id WHERE r.id=? AND r.event_id=?');$s->execute([$roundId,(int)$event['id']]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)throw new SeNotFoundException('Round not found.');$now=se_epoch_ms();$opens=strtotime($r['opens_at'])*1000+(int)substr($r['opens_at'],-3);$closes=strtotime($r['closes_at'])*1000+(int)substr($r['closes_at'],-3);if($now<$opens)throw new SeRuleException('Not yet — get ready.','TOO_EARLY');if($now>$closes+1500||in_array($r['state'],['locked','revealed','scored','void'],true))throw new SeRuleException("Time's up.",'ROUND_CLOSED');$item=se_round_item($pdo,$r);$choices=$item['payload']['choices']??[];$choice=se_int($in['choice_index']??-1,-1);if($choice<0||$choice>=count($choices))throw new SeValidationException('Choose one of the answers.',['choice_index']);$elapsed=se_game_elapsed(se_int($in['client_elapsed_ms']??0,0),$now-$opens,(int)($in['duration_ms']??20000));try{$s=$pdo->prepare('INSERT INTO se_answers(event_id,round_id,registration_id,team_id,role,choice_index,received_at,client_elapsed_ms,elapsed_ms,device_id) VALUES(?,?,?,?,?,?,?,?,?,?)');$s->execute([(int)$event['id'],$roundId,(int)$reg['id'],$reg['team_id']??null,($r['type']==='trivia'?'captain':'player'),$choice,date('Y-m-d H:i:s.v'),$in['client_elapsed_ms']??null,$elapsed,$in['device_id']??null]);}catch(PDOException $e){if((int)$e->errorInfo[1]===1062)throw new SeRuleException('Your answer is already locked in.','ALREADY_ANSWERED');throw $e;}return ['accepted'=>true,'elapsed_ms'=>$elapsed]; }
function se_game_suggest(PDO $pdo,array $event,array $reg,array $in):array { $round=se_int($in['round_id']??0,0);$choice=se_int($in['choice_index']??-1,-1);$s=$pdo->prepare("INSERT INTO se_answers(event_id,round_id,registration_id,team_id,role,choice_index,received_at,elapsed_ms) VALUES(?,?,?,?, 'suggestion',?,NOW(3),0) ON DUPLICATE KEY UPDATE choice_index=VALUES(choice_index),received_at=VALUES(received_at)");$s->execute([(int)$event['id'],$round,(int)$reg['id'],$reg['team_id']??null,$choice]);return ['accepted'=>true]; }
function se_game_buzz(PDO $pdo,array $event,array $reg,array $in):array {if(empty($reg['team_id']))throw new SeRuleException('You need a team to buzz.','NOT_ELIGIBLE');$round=se_int($in['round_id']??0,0);$s=$pdo->prepare('SELECT * FROM se_rounds WHERE id=? AND event_id=?');$s->execute([$round,(int)$event['id']]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)throw new SeNotFoundException('Round not found.');$now=se_epoch_ms();$opens=strtotime($r['opens_at'])*1000+(int)substr($r['opens_at'],-3);$client=se_int($in['client_ms']??$now,0);$effective=se_buzz_effective($client,$opens,$now);$s=$pdo->prepare('INSERT INTO se_buzzes(event_id,round_id,attempt,team_id,registration_id,effective_ms,received_at) VALUES(?,?,?,?,?,?,NOW(3))');try{$s->execute([(int)$event['id'],$round,$r['attempt'],(int)$reg['team_id'],(int)$reg['id'],$effective]);}catch(PDOException $e){if((int)$e->errorInfo[1]===1062)throw new SeRuleException('Your team already buzzed.','ALREADY_BUZZED');throw $e;}return ['accepted'=>true,'effective_ms'=>$effective];}
function se_live_game_payload(PDO $pdo,array $event):?array { if(!se_game_ready($pdo))return null;$s=$pdo->prepare("SELECT * FROM se_games WHERE event_id=? AND status IN ('live','ready') ORDER BY sort_order,id LIMIT 1");$s->execute([(int)$event['id']]);$g=$s->fetch(PDO::FETCH_ASSOC);if(!$g)return null;$q=$pdo->prepare("SELECT * FROM se_rounds WHERE game_id=? ORDER BY round_no DESC LIMIT 1");$q->execute([(int)$g['id']]);$r=$q->fetch(PDO::FETCH_ASSOC);return ['id'=>(int)$g['id'],'type'=>$g['type'],'title'=>$g['title'],'status'=>$g['status'],'settings'=>se_game_settings($g),'round'=>$r?se_round_public($pdo,$r,in_array($r['state'],['revealed','scored'],true)):null];}
