<?php
// /includes/special_events/scoring.php
// Append-only scoring ledger and leaderboards.

function se_quiz_points(int $base,int $elapsed,int $duration):int { if($base<=0)return 0;return max(0,(int)round($base*(1-(min($duration,max(0,$elapsed))/(float)max(1,$duration))/2))); }
function se_team_normalized_points(int $base,int $correct,int $eligible):int { return (int)round($base*$correct/max(1,$eligible)); }
function se_score_key(string $kind,int $round,int $subject,int $attempt=0):string { $scope=$kind==='q'?'p':'t'; return $kind.':'.$round.':'.$scope.':'.$subject.($attempt?':a:'.$attempt:''); }
function se_score_insert(PDO $pdo,array $event,array $in,int $actor):array { $scope=se_enum($in['scope']??'', ['team','individual'],'');if($scope==='')throw new SeValidationException('Score scope is required.',['scope']);$points=(int)($in['points']??0);$key=se_line($in['idempotency_key']??'',80)?:null;$s=$pdo->prepare('INSERT INTO se_score_events(event_id,scope,team_id,registration_id,game_id,round_id,kind,points,reason,idempotency_key,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE id=id');$s->execute([(int)$event['id'],$scope,$in['team_id']??null,$in['registration_id']??null,$in['game_id']??null,$in['round_id']??null,se_enum($in['kind']??'award',['auto','award','penalty','correction'],'award'),$points,se_line($in['reason']??'',160)?:null,$key,$actor]);$id=(int)$pdo->lastInsertId();if(!$id&&$key){$q=$pdo->prepare('SELECT id FROM se_score_events WHERE event_id=? AND idempotency_key=?');$q->execute([(int)$event['id'],$key]);$id=(int)$q->fetchColumn();}return ['id'=>$id,'points'=>$points,'idempotency_key'=>$key];}
function se_score_void(PDO $pdo,array $event,int $id,string $reason,int $actor):void {if(mb_strlen(trim($reason))<3)throw new SeValidationException('Give a reason for voiding a score.',['reason']);$s=$pdo->prepare('UPDATE se_score_events SET voided_at=NOW(),voided_by=?,void_reason=? WHERE id=? AND event_id=? AND voided_at IS NULL');$s->execute([$actor,$reason,$id,(int)$event['id']]);}
function se_leaderboards(PDO $pdo,array $event):array {if(!se_table_exists($pdo,'se_score_events'))return ['teams'=>[],'mvp'=>[]];$id=(int)$event['id'];$s=$pdo->prepare("SELECT team_id,SUM(points) points FROM se_score_events WHERE event_id=? AND scope='team' AND voided_at IS NULL GROUP BY team_id ORDER BY points DESC,team_id");$s->execute([$id]);$teams=$s->fetchAll(PDO::FETCH_ASSOC);$s=$pdo->prepare("SELECT registration_id,SUM(points) points FROM se_score_events WHERE event_id=? AND scope='individual' AND voided_at IS NULL GROUP BY registration_id ORDER BY points DESC,registration_id LIMIT 5");$s->execute([$id]);return ['teams'=>$teams,'mvp'=>$s->fetchAll(PDO::FETCH_ASSOC)];}
function se_round_score(PDO $pdo,array $event,int $roundId,int $actor):array { $s=$pdo->prepare('SELECT * FROM se_rounds WHERE id=? AND event_id=?');$s->execute([$roundId,(int)$event['id']]);$round=$s->fetch(PDO::FETCH_ASSOC);if(!$round)throw new SeNotFoundException('Round not found.');if($round['state']!=='revealed')throw new SeRuleException('Reveal the round before scoring.','ROUND_NOT_REVEALED');$item=se_round_item($pdo,$round);$payload=$item['payload']??[];$correct=(int)($payload['answer_index']??-1);$q=$pdo->prepare('SELECT * FROM se_answers WHERE round_id=? AND role IN ("player","captain")');$q->execute([$roundId]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);$n=0;foreach($rows as $a){$ok=$correct>=0&&(int)$a['choice_index']===$correct;$points=$ok?se_quiz_points(1000,(int)$a['elapsed_ms'],20000):0;$se_score=['scope'=>'individual','registration_id'=>(int)$a['registration_id'],'game_id'=>(int)$round['game_id'],'round_id'=>$roundId,'kind'=>'auto','points'=>$points,'idempotency_key'=>'q:'.$roundId.':p:'.$a['registration_id']];se_score_insert($pdo,$event,$se_score,$actor);$n++;if($ok&&$a['team_id'])se_score_insert($pdo,$event,['scope'=>'team','team_id'=>(int)$a['team_id'],'game_id'=>(int)$round['game_id'],'round_id'=>$roundId,'kind'=>'auto','points'=>1000,'idempotency_key'=>'q:'.$roundId.':t:'.$a['team_id']],$actor);}$pdo->prepare("UPDATE se_rounds SET state='scored' WHERE id=? AND state='revealed'")->execute([$roundId]);return ['answers'=>$n,'leaderboard'=>se_leaderboards($pdo,$event)];}
